- id: nbwipers-check-install
  name: nbwipers check install
  description: Check nbwipers is installed
  entry: nbwipers check-install
  args: []
  language: python
  stages: [commit, merge-commit, push, manual]
  always_run: true
  pass_filenames: false
- id: nbwipers-check-wd
  name: nbwipers check wd
  description: Check notebooks are clean in your working directory
  entry: nbwipers clean-all
  args: []
  language: python
  stages: [commit, merge-commit, push, manual]
  types_or: [jupyter]
  require_serial: true
- id: nbwipers-large-files
  name: nbwipers large files
  description: Check for large files in repository, but clean notebooks before checking
  entry: nbwipers hook check-large-files
  args: []
  language: python
  stages: [commit, push, manual]
- id: nbwipers-record
  name: nbwipers record kernel info
  description: Check nbwipers is installed
  entry: nbwipers record
  args: []
  language: python
  stages: [commit, merge-commit, push, manual]
  always_run: true
  pass_filenames: false
